title:             Barry the Cat
email:             email@example.com
description:       A Blog Theme by Start Bootstrap
author:            jraleman
baseurl:           "/barry"
url:               "https://jraleman.com"

# Social Profiles
#twitter_username:  SBootstrap
github_username:   jraleman
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

theme: jekyll-theme-merlot